Hw4
apxunov/HSE-React pull request #2
Opened 2021-04-26 12:45 UTC by apxunov

Сделал TaskAdd и TaskInput компоненты. Кнопки и добавление пока не работают

2021-04-26 18:34 UTC, apxunov reviewed
Реализовал вывод новых тасков

2021-05-08 09:48 UTC, ValeryStatinov requested changes

2021-05-08 09:48 UTC, ValeryStatinov commented on src/App.js
> +  constructor(props) {
использование конструктора и вызов super необязательно в новом систаксисе
```
class MyClass extends React.Component {
  state = { ... }
  otherField = 10

  method = () => { ... }
  
  render() {
    retutn ...
  }
}
```

2021-05-08 09:48 UTC, ValeryStatinov commented on src/App.js
> +      newTasksList[taskID-1] = { ...newTasksList[taskID-1], completed: !currentState.tasks[taskID-1].completed } // инвертируем булевое значение
1) мутация стейта!!! `newTasksList === currentState.tasks // false`, НО `newTasksList[0] === currentState.tasks[0] // true`, тк spread оператор делает shallow копирование

2) taskID-1 - неуниверсальное решение. при дальнейшем подключении к беку id задач будут идти не по порядку, а будут просто случайными числами (на самом деле не случайными, но с точки зрения фронта - случайными). нужно искать нужную таску через `findIndex`

2021-05-08 09:48 UTC, ValeryStatinov commented on src/App.js
> +    const name = document.getElementsByName('taskName')[0].value // инпут названия таска
это vanilla js решение, но не react-way. в реакте мы не ищем элементы через `document.getElementsByName` и тд (только в index.js в вызове `ReactDOM.render`)

2021-05-08 09:48 UTC, ValeryStatinov commented on src/App.js
> +    const taskID = clickedBtn.closest('div').id // получаем id Task'а
нужно в `handleTaskStatus` передавать `id` таски, на которую нажали

2021-05-08 09:48 UTC, ValeryStatinov commented on src/components/TaskAdd/TaskAdd.js
> +        <form className={cls.join(' ')}>
почему бы не сделать просто `className={classes.task}`? но вообще это тема след домашки, так что пока ОК и так:)

2021-05-08 09:48 UTC, ValeryStatinov commented on src/components/TaskInput/TaskInput.js
> +              isRequired='1'
лучше тогда сделать `isRequired` типом boolean

2021-05-08 09:48 UTC, ValeryStatinov commented on src/components/TaskInput/TextInput/TextInput.js
> +                name={`${name}`}
можно просто `name={name}`

2021-05-08 20:04 UTC, ValeryStatinov approved these changes

2021-05-08 20:04 UTC, ValeryStatinov commented on src/components/Task/Task.js
> +          { completed ? <Button btnName='Undone' onClick={() => onClick(id)}/> : <Button btnName='Done' onClick={() => onClick(id)}/> }
можно немного упростить
```
<Button btnName={completed ? 'Done' : 'Undone'} ... />
```

2021-05-08 20:04 UTC, ValeryStatinov commented on src/components/TaskInput/TaskInput.js
> +              isRequired='true'
ну тип то остался строковый) `isRequired={true/false}`

более того, если тип boolean и нужно значение `true`, то его можно вообще не указывать
```
<Comp isRequired /> // означает, что isRequired === true
```

2021-05-08 20:05 UTC, ValeryStatinov commented
отл(8)

2021-05-08 20:05 UTC, merged